version: "3.2"
services:
    globaleaks:
      container_name: globaleaks
      build: .
      image: tsundokul/globaleaks
      ports:
        - '7080:80'
        - '7443:443'
      volumes:
        - 'globaleaks:/var/globaleaks'
        - 'tor:/var/lib/tor'

volumes:
  globaleaks: {}
  tor: {}
