version: "3.2"
services:
    globaleaks:
      container_name: globaleaks
      build: .
      image: tsundokul/globaleaks
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - 'globaleaks:/var/globaleaks'
        - 'tor:/var/lib/tor'

volumes:
  globaleaks: {}
  tor: {}
